apps:
  - script   : ./index.js
    name     : 'okapiuptime'
    watch  : true
    ignore_watch:
      - 'data/okapiuptime.db'
      - 'data/okapiuptime.db-journal'
      - 'data/okapiuptime.db-wal'
    watch_options:
      followSymlinks: false
    env    :
      NODE_ENV: production
      CRON_EXP: 5 * * * * *
      PORT: 80
